/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import ConecBD.ConexaoBanco;
import Controles.CadastroFControle;
import Entidades.Financa;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.Color;
import javax.swing.border.TitledBorder;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import java.text.SimpleDateFormat;

/**
 * Tela de cadastro de finanças, mas também é alterada para funcionar como todos os outros métodos (Consulta, exclusão, modificação e quitação)
 *
 * @author Maycon
 */
public class CadastroFinancas extends javax.swing.JFrame {
    public TelaPrincipal telaanterior;
    public int metodo;
    Connection confinanca = null;
    private int financaId=-1;

    String title;
    /**
     * 19/12 - Maycon Creates new form TelaServicos
     */
    private CadastroFinancas() {
        initComponents();

        //Seta janela para o meio da tela, independente da resolução.
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        IDField.setEnabled(false);
        title = this.getTitle();
        initNoicon(); //Seta "Logo vazio".
    }

    /**
     * 06/01/16 - Juliano Felipe Seta icone 1*1px (para "remover" icone default)
     */
    private void initNoicon() {
        Image No_ico = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB_PRE);
        this.setIconImage(No_ico);
    }

    /**
     * 03/02/16 - Juliano Felipe "Pseudo-construtor", chama o construtor padrão,
     * função de reutilização de jFrame e salva a instância do jFrame que chamou
     * este (para poder habilitá-lo quando esta tela é fechada.
     *
     * @param telanterior - Instância da tela anterior.
     * @param option - Modo que o jFrame será utilizado (1 para Cadastro, 2 para
     * consulta, etc).
     */
    public CadastroFinancas(TelaPrincipal telanterior, int option) {
        //Chamar construtor
        this();
        this.telaanterior = telanterior;
        metodo = option;
        metodosFinancas(option);
    }

    /**
     * 06/01/16 - Juliano Felipe Define metodos sobre a janela finacas,
     * reutilizando a mesma Variavel op chama o respectivo metodo
     *
     * @param op - Opção de reutilização 1 - Cadastro (esse método não é
     * chamado, devido a condição de chamada no construtor modificado); 2 -
     * Consulta; 3 - Modificação; 4 - Exclusão;
     */
    public void metodosFinancas(int op) {
        //confinanca = ConexaoBanco.confinanca();
        //SelectButton.setEnabled (false);
        if (op == 1) {//Op==1 - Consultar
            SitToggle.setEnabled(false);
            SelectButton.setEnabled(false);
            PanelColor(1, Color.GRAY);
        }
        if (op >= 2) {
            this.setTitle("Consulta de finanças");
            jFormattedTextField2.setEnabled(false);
            jRadioButton1.setEnabled(false);
            jRadioButton2.setEnabled(false);
            jCheckBox1.setEnabled(false);
            jDateChooser1.setEnabled(false);
            jTextPane2.setEnabled(false);
            jButton2.setText("Consultar");
            //Para o cliente não confundir os botões
            jButton2.setEnabled(false); //de consulta
        }
        if (op == 3) {//Op==3 - Modificar
            this.setTitle("Modificação de finanças");
        }
        if (op == 4) {//Op==4 - Excluir
            this.setTitle("Exclusão de finanças");
        }
        if (op == 5) {//Op==5 - Quitar
            this.setTitle("Quitar finanças");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        ValorPanel = new javax.swing.JPanel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        TipoPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        DataPanel = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        DescPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        SitPanel = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        SelectPanel = new javax.swing.JPanel();
        SitToggle = new javax.swing.JToggleButton();
        SelectButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        IDField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de finanças");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        ValorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor"));

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        javax.swing.GroupLayout ValorPanelLayout = new javax.swing.GroupLayout(ValorPanel);
        ValorPanel.setLayout(ValorPanelLayout);
        ValorPanelLayout.setHorizontalGroup(
            ValorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextField2)
        );
        ValorPanelLayout.setVerticalGroup(
            ValorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ValorPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TipoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Receita");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Despesa");

        javax.swing.GroupLayout TipoPanelLayout = new javax.swing.GroupLayout(TipoPanel);
        TipoPanel.setLayout(TipoPanelLayout);
        TipoPanelLayout.setHorizontalGroup(
            TipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TipoPanelLayout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TipoPanelLayout.setVerticalGroup(
            TipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton1)
                .addComponent(jRadioButton2))
        );

        DataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        javax.swing.GroupLayout DataPanelLayout = new javax.swing.GroupLayout(DataPanel);
        DataPanel.setLayout(DataPanelLayout);
        DataPanelLayout.setHorizontalGroup(
            DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );
        DataPanelLayout.setVerticalGroup(
            DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataPanelLayout.createSequentialGroup()
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        DescPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));

        jTextPane2.setToolTipText("Qualquer observação adicional.");
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout DescPanelLayout = new javax.swing.GroupLayout(DescPanel);
        DescPanel.setLayout(DescPanelLayout);
        DescPanelLayout.setHorizontalGroup(
            DescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        DescPanelLayout.setVerticalGroup(
            DescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
        );

        SitPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Situação"));

        jCheckBox1.setText("Pago");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SitPanelLayout = new javax.swing.GroupLayout(SitPanel);
        SitPanel.setLayout(SitPanelLayout);
        SitPanelLayout.setHorizontalGroup(
            SitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SitPanelLayout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SitPanelLayout.setVerticalGroup(
            SitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCheckBox1)
        );

        jButton2.setText("Salvar");
        jButton2.setMaximumSize(new java.awt.Dimension(75, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(75, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SelectPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)), "Consultar Finança"));

        SitToggle.setText("Não pago");
        SitToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SitToggleActionPerformed(evt);
            }
        });

        SelectButton.setText("Consultar");
        SelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SelectPanelLayout = new javax.swing.GroupLayout(SelectPanel);
        SelectPanel.setLayout(SelectPanelLayout);
        SelectPanelLayout.setHorizontalGroup(
            SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectPanelLayout.createSequentialGroup()
                .addComponent(SitToggle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(SelectButton))
        );
        SelectPanelLayout.setVerticalGroup(
            SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SitToggle)
                    .addComponent(SelectButton)))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));

        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IDField, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DescPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TipoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ValorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SelectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ValorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SelectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TipoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DescPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                    .addComponent(SitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 11/02/16 - Juliano Felipe
     * Função para consulta de finanças no banco de dados.
     * @param situacao (Pago ou não pago). Seleciona todas as entradas no banco com os tais params.
     * @return rowid da finança.
     */
    private int selectFinanca (String situacao){
        this.setEnabled(false);
        String []columnNames = {"rowid","tipo","data","valor","sit","Obs"};
        MultipleTable MServiceTable = new MultipleTable (this, columnNames, situacao);
        MServiceTable.setVisible(true);
        
        //Gets
        int rowid = MServiceTable.getId();
        Object[] rowDados = MServiceTable.getRow();
        
        String tmp = rowDados[1].toString();
        if (tmp.equals("Receita")){
            jRadioButton1.setSelected(true);
            jRadioButton2.setSelected(false);
        } else if (tmp.equals("Despesa")){
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(true);
        }
        
        try{
            java.util.Date date = new SimpleDateFormat("dd/MM/yyyy").parse(rowDados[2].toString());
            jDateChooser1.setDate(date);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro. Código: 04-03-03.", title, JOptionPane.ERROR_MESSAGE);
            //System.err.println(Arrays.toString(e.getStackTrace()));
            System.err.println("04-03-03: " + e.getClass().getName() + ": " + e.getMessage());
        }
            
        jFormattedTextField2.setText(rowDados[3].toString());
                
        tmp = rowDados[4].toString();
        if (tmp.equals("Quitado")){
            jCheckBox1.setSelected(true);
        } else if (tmp.equals("Pendente")){
            jCheckBox1.setSelected(false);
        }
        
        jTextPane2.setText(rowDados[5].toString());
        
        MServiceTable.parafechar.dispose();
        
        IDField.setText(""+rowid);
        return rowid;
    }
    
    private void updateFinanca(boolean tipo, String data, double valor, boolean sit, String obs, int rowid) throws Exception{
        if (rowid==-1){
            JOptionPane.showMessageDialog(this, "Erro. Código: 04-03-04.", title, JOptionPane.ERROR_MESSAGE);
            return;
        }
        confinanca = ConexaoBanco.confinanca();
        if (confinanca==null) System.err.println("Conn Null");
        PreparedStatement pst = null;
        try {
            String sql1 = "UPDATE financa SET tipo=?, data=?, valor=?, sit=?, obs=? WHERE rowid="+rowid;
            pst = confinanca.prepareStatement(sql1);
                    if (pst==null) System.err.println ("PST NULL");
                    System.out.println(tipo);
            pst.setBoolean(1, tipo);
            pst.setString (2, data);
            pst.setDouble (3, valor);
            pst.setBoolean(4, sit);
            pst.setString (5, obs);
            pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro. Código: 04-03-05.", title, JOptionPane.ERROR_MESSAGE);
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            //System.exit(0);
        } finally {
            if (pst != null) 
                pst.close();
            if (confinanca != null) 
                confinanca.close();
        }
    } 
    
    private void insertFinanca(boolean tipo, String data, double valor, boolean sit, String obs) throws Exception{
        confinanca = ConexaoBanco.confinanca();
        PreparedStatement pst = null;
        try {
            String sql1 = "Insert into financa (tipo,data,valor,sit,obs) values (?,?,?,?,?)";
            pst = confinanca.prepareStatement(sql1);
            pst.setBoolean(1, tipo);
            pst.setString (2, data);
            pst.setDouble (3, valor);
            pst.setBoolean(4, sit);
            pst.setString (5, obs);
            pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro. Código: 04-03-01", title, JOptionPane.ERROR_MESSAGE);
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            System.exit(0);
        } finally {
            if (pst != null) 
                pst.close();
            if (confinanca != null) 
                confinanca.close();
        }
    }

    /**
     * 06/02/16 - Juliano Felipe 
     * Método para pegar a data do jDayChooser (pertencente ao jCalendar)
     * e transformar no padrão salvo no banco de dados.
     * 
     * @param date - Data a ser transformada para o padrão (obtida por 
     * ".getDate().toString();")
     * 
     * @return String de data no formato estipulado
     */
    private String getJDate(String date){
        String[] split = date.split(" ",6);     //split by spaces        
        String day = split[2]; 
        String month = split[1];
        String year = split[5];
        
        switch (month) {
            case "Jan":
                month = "01";
                break;
            case "Feb":
                month = "02";               
                break;
            case "Mar":
                month = "03";                
                break;
            case "Apr":
                month = "04";                
                break;
            case "May":
                month = "05";                
                break;
            case "Jun":
                month = "06";                
                break;
            case "Jul":
                month = "07";                
                break;
            case "Aug":
                month = "08";                
                break;
            case "Sep":
                month = "09";                
                break;
            case "Oct":
                month = "10";                
                break;
            case "Nov":
                month = "11";                
                break;
            case "Dec":
                month = "12";                
                break;
            }
        
        return day + "/" + month + "/" + year;
    }
    
    /**
     * 06/02/16 - Juliano Felipe 
     * Método para pegar a String do "jFormattedTextField2"
     * e transformá-la no padrão salvo no banco de dados (double).
     * 
     * @param valorText - String a ser transformada para o padrão double.
     * 
     * @return valor double convertido.
     */
    private double getValor (String valorText){
        //Split nas vírgulas - Exemplo: 1,234.00  --> 1234.00
        String[] split = valorText.split(","); //Split on commas
        int i,j = split.length; //Contagem de "trios separados por virgulas"
        valorText=""; //String passada por parâmetro não mais necessária,
                     //A inicializa para ser "convertida".
        for (i=0; i<j; i++){
            valorText+=split[i]; //Concatena-se as partes
        }
        
        return Double.parseDouble(valorText);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Trecho de Modificar finanças. Consulta, lista, habilita edição, salva, e chama o "refresh"
        //(para outra modificação sem fechar a janela).       
        if (metodo == 3) {
            String flag = jButton2.getText();
            System.out.println(flag);
            if (!flag.equals("Modificar")){
                System.out.println("ENTRA AQUI?");
                financaId = selectFinanca (SitToggle.getText());
                if (financaId==-1){
                    JOptionPane.showMessageDialog(this, "Erro. Código: 04-03-06.", title, JOptionPane.ERROR_MESSAGE);
                    return;
                }
                jFormattedTextField2.setEnabled(true);
                jRadioButton1.setEnabled(true);
                jRadioButton2.setEnabled(true);
                jCheckBox1.setEnabled(true);
                jDateChooser1.setEnabled(true);
                jTextPane2.setEnabled(true);
            }else{
                boolean rec = jRadioButton2.isSelected();
                boolean des = jRadioButton1.isSelected();
                boolean tipo = false;
                if (rec == true) {
                    tipo = true;
                } else if (des == true) {
                    tipo = false;
                }
                System.out.println (IDField.getText());
                try {
                    updateFinanca (tipo, getJDate(jDateChooser1.getDate().toString()), getValor (jFormattedTextField2.getValue().toString()),  jCheckBox1.isSelected(), jTextPane2.getText(), Integer.parseInt(IDField.getText()));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Erro. Código: 04-03-07.", title, JOptionPane.ERROR_MESSAGE);
                    System.err.println(e.getClass().getName() + ": " + e.getMessage());
                }
                
                metodosFinancas(3); //Resetar modificação
                return;
            }
            jButton2.setText("Modificar");
            return;
        }
        
        //Trecho de excluir finanças. Consulta e exclui
        if (metodo == 4) {
            String flag = jButton1.getText();
            if (!flag.equals("Excluir")){
                financaId = selectFinanca (SitToggle.getText());
                if (financaId==-1){
                    JOptionPane.showMessageDialog(this, "Erro. Código: 04-03-08.", title, JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }else{
                try {
                    String sql1 = "DELETE FROM servico WHERE rowid="+financaId;
                    PreparedStatement pst = confinanca.prepareStatement(sql1);            
                    pst.execute();
                    confinanca.close();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Erro. Código: 04-03-09.", title, JOptionPane.ERROR_MESSAGE);
                    System.err.println(e.getClass().getName() + ": " + e.getMessage());
                    System.exit(0);
                }
                
                jButton2.setEnabled(false); //Para não tentar Excluir novamente
                jButton1.setText("Sair");
            }
            jButton2.setText("Excluir");
            return;
        }
        
        //Trecho de quitar finanças. Consulta os dados e força salvar com a situação em true (Pago)
        if (metodo==5){
            String flag = jButton1.getText();
            if (!flag.equals("Quitar")){
                financaId = selectFinanca (SitToggle.getText());
                if (jCheckBox1.isSelected()){
                    JOptionPane.showMessageDialog(this, "Finança já quitada.\nCódigo: 04-03-0A.", title, JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (financaId==-1){
                    JOptionPane.showMessageDialog(this, "Erro. Código: 04-03-0B.", title, JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }else{
                boolean rec = jRadioButton2.isSelected();
                boolean des = jRadioButton1.isSelected();
                boolean tipo = false;
                if (rec == true) {
                    tipo = true;
                } else if (des == true) {
                    tipo = false;
                }
                try {
                    updateFinanca (tipo, getJDate(jDateChooser1.getDate().toString()), getValor (jFormattedTextField2.getValue().toString()),  jCheckBox1.isSelected(), jTextPane2.getText(), financaId);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Erro. Código: 04-03-0C.", title, JOptionPane.ERROR_MESSAGE);
                    System.err.println(e.getClass().getName() + ": " + e.getMessage());
                }
                
                metodosFinancas(5); //Resetar modificação
                return;
            }
            jButton2.setText("Quitar");
            return;
        }

        //Botão Salvar pressionado
        /**
         * 06/01/16 - Juliano Definido a opcao 2 (consultar), altera-se a funcao
         * do botao salvar 03/02/16 - Maycon Apagada funcao do Juliano, colar
         * quando fizer-se necessario
         */
        //Botão Salvar pressionado
        double valor = getValor (jFormattedTextField2.getValue().toString());
        
        String data = getJDate(jDateChooser1.getDate().toString());
        
        boolean sit = jCheckBox1.isSelected();
        boolean tipo = false;
        if (jRadioButton2.isSelected()) {
            tipo = true;
        } else if (jRadioButton1.isSelected()) {
            tipo = false;
        } else {
            System.err.println("Erro. Código: 04-03-0D.\nNenhum tipo selecionado");
            return;
        }
        String obs = jTextPane2.getText();

        Financa p = new Financa(tipo, data, valor, obs, sit);
        //Chama o controle para cadastrar
        CadastroFControle C = new CadastroFControle();

        /**
         * 03/02 - Maycon TESTE PARA VERIFICAÇÃO SE OS DADOS DA FINANCA FORAM
         * RECEBIDOS
         *
         */
        System.out.println("Valor: " + valor);
        System.out.println("Data: " + data);
        System.out.println("Tipo: " + tipo);
        System.out.println("Situacao: " + sit);
        System.out.println("Obs: " + obs);
        /**
         * FIM DO TESTE!!!!
         */

        if (C.cadastrarfinanca(p)) {
            //Insere no banco de dados
            try {
                insertFinanca(tipo, data, valor, sit, obs);            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro. Código: 04-03-0E.", title, JOptionPane.ERROR_MESSAGE);
                System.err.println(e.getClass().getName() + ": " + e.getMessage());
            }
            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso", title, JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            telaanterior.setEnabled(true);
            telaanterior.requestFocus(); //Traz o foco para tela anterior
        } else {
            JOptionPane.showMessageDialog(this, "Erro. 04-03-02", title, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Botão Cancelar pressionado
        this.dispose();
        telaanterior.setEnabled(true);
        telaanterior.requestFocus(); //Traz o foco para tela anterior
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        /**
         * 05/01 - Maycon Tela fechada
         */
        telaanterior.RefreshTable();
        telaanterior.setEnabled(true);
        telaanterior.requestFocus(); //Traz o foco para tela anterior
    }//GEN-LAST:event_formWindowClosed

    /**
    * 06/02/16 - Juliano Felipe 
    * Método para alterar a cor dos painéis.
    * Coloca uma borda igual a padrão, no entando, altera-se a cor.
    * 
    * @param Borda Int dizendo qual borda deve ser pintada.
    * @param cor para pintar a borda.
    */
    private void PanelColor (int Borda, Color cor){
        String[] titles = {"Valor", "Consultar Finança", "Tipo", "Situação", "Data", "Descrição"};
        Border line = BorderFactory.createLineBorder(cor);
        TitledBorder Brdr = BorderFactory.createTitledBorder(line,titles[Borda]);
        Brdr.setTitleJustification(TitledBorder.LEFT);
        Brdr.setTitlePosition(TitledBorder.TOP);
        switch (Borda) {
            case 0:
                ValorPanel.setBorder (Brdr);
                break;
            case 1:
                SelectPanel.setBorder (Brdr);
                break;
            case 2:
                TipoPanel.setBorder (Brdr);
                break;
            case 3:
                SitPanel.setBorder (Brdr);
                break;
            case 4:
                DataPanel.setBorder (Brdr);
                break;
            case 5:
                DescPanel.setBorder (Brdr);
                break;
            }
    }
    
    private void SelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButtonActionPerformed
        String modo = SitToggle.getText();
        selectFinanca (modo);
        PanelColor (1,Color.GREEN);
        String method = null;
        switch(metodo){
            case 2: //Sair sem habilitar o botão
                return; //e sem alterar o texto.
            case 3:
                method = "Modificar";
                jFormattedTextField2.setEnabled(true);
                jRadioButton1.setEnabled(true);
                jRadioButton2.setEnabled(true);
                jCheckBox1.setEnabled(true);
                jDateChooser1.setEnabled(true);
                jTextPane2.setEnabled(true);
                break;
            case 4:
                method = "Excluir";
                break;
            case 5:
                method = "Quitar";
                break;
            default:
                System.out.println ("Erro. Código: 04-03-0F. Variável métodos inválida");
        }
        jButton2.setText(method);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_SelectButtonActionPerformed

    private void SitToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SitToggleActionPerformed
        //Botão toggle da situação
        if (SitToggle.isSelected()){
            SitToggle.setText("    Pago    ");
        } else {
            SitToggle.setText("Não pago");
        }
    }//GEN-LAST:event_SitToggleActionPerformed

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFinancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFinancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFinancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFinancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFinancas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataPanel;
    private javax.swing.JPanel DescPanel;
    private javax.swing.JTextField IDField;
    private javax.swing.JButton SelectButton;
    private javax.swing.JPanel SelectPanel;
    private javax.swing.JPanel SitPanel;
    private javax.swing.JToggleButton SitToggle;
    private javax.swing.JPanel TipoPanel;
    private javax.swing.JPanel ValorPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
