/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tolteco.sigma.view;

import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import tolteco.sigma.controller.UsuarioController;
import tolteco.sigma.model.dao.DatabaseException;
import tolteco.sigma.model.entidades.Usuario;
import tolteco.sigma.model.entidades.Version;

/**
 * Tela de Login do sistema.
 * @author Juliano Felipe
 */
public class Login extends javax.swing.JFrame {
    private final List<Usuario> usuariosPossiveis;
    private final UsuarioController controller;
    private final Version latestVersion;
    
    /**
     * Creates new form TelaLogin
     * @param controller
     * @param latestVersion
     * @throws tolteco.sigma.model.dao.DatabaseException
     */
    public Login(UsuarioController controller, Version latestVersion) throws DatabaseException {
        initComponents();
        this.controller = controller;
        this.latestVersion = latestVersion;
        
        try {
            usuariosPossiveis = controller.selectAll();
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao obter usuários do Banco de dados.", "Finalizando...", JOptionPane.ERROR_MESSAGE);
            throw new DatabaseException(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        UsuárioPanel = new javax.swing.JPanel();
        Usuarios = new javax.swing.JComboBox();
        SenhaPanel = new javax.swing.JPanel();
        SenhaField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        SigmaIcoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        SigmaLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        VersaoLabel = new javax.swing.JLabel();
        versionNumberLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        UsuárioPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário"));

        Usuarios.setEditable(true);

        javax.swing.GroupLayout UsuárioPanelLayout = new javax.swing.GroupLayout(UsuárioPanel);
        UsuárioPanel.setLayout(UsuárioPanelLayout);
        UsuárioPanelLayout.setHorizontalGroup(
            UsuárioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Usuarios, 0, 138, Short.MAX_VALUE)
        );
        UsuárioPanelLayout.setVerticalGroup(
            UsuárioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuárioPanelLayout.createSequentialGroup()
                .addComponent(Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        SenhaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));

        javax.swing.GroupLayout SenhaPanelLayout = new javax.swing.GroupLayout(SenhaPanel);
        SenhaPanel.setLayout(SenhaPanelLayout);
        SenhaPanelLayout.setHorizontalGroup(
            SenhaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SenhaField)
        );
        SenhaPanelLayout.setVerticalGroup(
            SenhaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SenhaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        LoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tolteco/sigma/view/images/User/LogIn.png"))); // NOI18N
        LoginButton.setText("Entrar");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        SigmaIcoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tolteco/sigma/view/images/Logo 100x100.png"))); // NOI18N
        SigmaIcoLabel.setText(" ");

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 3));

        SigmaLabel.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        SigmaLabel.setText("      SIGMA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SigmaIcoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(SigmaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SenhaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UsuárioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(LoginButton)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(SigmaIcoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SigmaLabel)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(UsuárioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SenhaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)
                            .addComponent(LoginButton))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator2.setMinimumSize(new java.awt.Dimension(50, 3));
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 3));

        VersaoLabel.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        VersaoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VersaoLabel.setText("VERSÃO");

        versionNumberLabel.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        versionNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionNumberLabel.setText("1.0 (SANTIAGO)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(VersaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versionNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VersaoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(versionNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * 10/01/16 - Juliano Felipe
    * Inicialização da tela de login
    */
    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String userName = (String)Usuarios.getSelectedItem();

        Usuario toLogin = null; // Usuário a entrar no sistema
        for (Usuario usuario : usuariosPossiveis){
            if (usuario.getUserName().equals(userName)){
                toLogin = usuario;
            }
        }

        if (toLogin == null) 
            JOptionPane.showMessageDialog(null, "Erro. Usuário e/ou senha inválidos.", "Acesso negado", JOptionPane.ERROR_MESSAGE);
        else{
            char[] pass = SenhaField.getPassword();
            
            if (Arrays.equals(pass, toLogin.getPass())) 
                executeLogin(toLogin);
            else
                JOptionPane.showMessageDialog(null, "Erro. Usuário e/ou senha inválidos.", "Acesso negado", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ViewUtils.centerFrame(this);
        ViewUtils.setSIGMAIcon(this);
        
        /*Adiciona todos os usuarios que não são ROOTs ao Combo*/
        usuariosPossiveis.forEach((user) -> {
            Usuarios.addItem(user.getUserName());
        });
        
        versionNumberLabel.setText( latestVersion.shortString() );
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField SenhaField;
    private javax.swing.JPanel SenhaPanel;
    private javax.swing.JLabel SigmaIcoLabel;
    private javax.swing.JLabel SigmaLabel;
    private javax.swing.JComboBox Usuarios;
    private javax.swing.JPanel UsuárioPanel;
    private javax.swing.JLabel VersaoLabel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel versionNumberLabel;
    // End of variables declaration//GEN-END:variables

    private void executeLogin(Usuario toLogin) {
        Usuario whoWillUse = new Usuario(toLogin); //Copy, as other instances will be destroyed - JF
        
        /*Clear every password manually*/
        usuariosPossiveis.stream().forEach((usuario) -> {
            usuario.clearPass();
        });
        
        /*ENTER THE SYSTEM HERE*/
        Sistema.login(whoWillUse, controller);
        this.dispose();
    }
}
