/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tolteco.sigma.view;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JPanel;
import net.java.balloontip.BalloonTip;
import tolteco.sigma.utils.DefaultConfigs;
import tolteco.sigma.view.cliente.MainCliente;
import tolteco.sigma.view.financas.MainFinanca;

/**
 *
 * @author Juliano
 */
public class MainFrame extends javax.swing.JFrame {
    private static final int accessLevel = 0; //Usado para testes - Nivel de acesso
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        JPanel panel = new MainView();
        PainelGuias.add(panel);
        PainelGuias.setTitleAt(0, "Principal");
        
        JPanel panel1 = new MainCliente();
        PainelGuias.add(panel1);
        PainelGuias.setTitleAt(1, "Clientes");
        
        JPanel panel2 = new MainFinanca();
        PainelGuias.add(panel2);
        PainelGuias.setTitleAt(2, "Finanças");
        
        if (accessLevel == 0){
            JMenu jmenu = new JMenu("Configurações");
            BarraDeMenu.add(Box.createHorizontalGlue());
            BarraDeMenu.add(jmenu);
        }
        
        JButton logOut = new JButton("Logout");
        logOut.setIcon(
            new javax.swing.ImageIcon(
                getClass().getResource("/tolteco/sigma/view/images/User/LogOut.png")));
        logOut.setPreferredSize( new Dimension (100,26));
        BarraDeMenu.add(logOut);
        
        JButton exit = new JButton("Sair");
        exit.setIcon(
            new javax.swing.ImageIcon(
                getClass().getResource("/tolteco/sigma/view/images/User/SystemOut.png")));
        exit.setPreferredSize( new Dimension (90,26));
        BarraDeMenu.add(exit);
        //BalloonTip bal = new BalloonTip(panel, "Tooltip msg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelGuias = new javax.swing.JTabbedPane();
        BarraDeMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGMA");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PainelGuias.setMinimumSize(new java.awt.Dimension(887, 580));

        jMenu1.setText("File");
        BarraDeMenu.add(jMenu1);

        jMenu2.setText("Edit");
        BarraDeMenu.add(jMenu2);

        setJMenuBar(BarraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelGuias, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelGuias, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ViewUtils.centerFrame(this);
        ViewUtils.setSIGMAIcon(this);
    }//GEN-LAST:event_formWindowOpened

    /**
     * Método principal para a criação de um frame.
     * Coloca o sistema no "look and feel" de acordo
     * com:
     * {@link tolteco.sigma.view.MainFrame#LOOKANDFEEL}.
     * Chama o construtor default para inicialização
     * de componentes.
     * @param args the command line arguments
     */
    public static void main(String args[]) {       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (DefaultConfigs.SYSTEMLOOK.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraDeMenu;
    private javax.swing.JTabbedPane PainelGuias;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables
}
